theme: jekyll-theme-slate
title: D -
description: o g
author: Devrim Demiroz

social:
  name: Devrim Demiroz
  links:
    - https://www.linkedin.com/in/ulasdevrimdemiroz/
    - https://github.com/devrimdemiroz/

google_verify:  uBST5lixEv3ZMZra_KZUcvypizVirBjpODWixQRaVOs

plugins:
  - jekyll-seo-tag