theme: jekyll-theme-slate
title: D-log
description: Tracing “Contact Tracing”
author: Devrim Demiroz

social:
  name: Devrim Demiroz
  links:
    - https://www.linkedin.com/in/ulasdevrimdemiroz/
    - https://github.com/devrimdemiroz/

google_verify:  uBST5lixEv3ZMZra_KZUcvypizVirBjpODWixQRaVOs
image: assets/images/covid-19.jpeg

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap